(1-2)初級 入力値エラー処理、(1-3)中級 Eメール重複チェック
sasagawa-ryuya/ex-emp-management-bugfix pull request #5
Opened 2022-06-09 06:42 UTC by sasagawa-ryuya

管理者登録フォームで以下の条件のとき、エラーメッセージを表示する機能を追加。
・氏名が空欄
・メールアドレスが空欄
・メールアドレスが既に使われている
・パスワードが空欄

--------------
1-3を先に進めたら、1-2もできてしまったのでまとめてプルリクエストします。

2022-06-09 07:43 UTC, sasagawa-ryuya commented
(1-5)中級 確認用パスワードも追加でpushしました。

2022-06-09 22:19 UTC, igamasayuki requested changes
1-2はレビューOKです。

1-3,1-5に関しては気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 22:19 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		}
resultにエラーメッセージを登録できていて汎用性が高く良いと思います。

2022-06-09 22:19 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +//		NOTE: フォームに空欄がある(result.hasError()がtrue)だと、パスワード不一致やメールアドレス重複のエラーメッセージが表示されない。
NOTEメモありがとうございます。
笹川さんが認識されているように

現在のエラーだと、入力値エラーが全部解消した後に、メールアドレス重複チェックのエラーが出ることになるため、
全部のエラーメッセージが同時に出るように改修をお願いします。

2022-06-09 22:19 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +			result.rejectValue("mailAddress", null, "そのメールアドレスは既に使われています");
resultにエラーメッセージを登録できていて汎用性が高く良いと思います。

2022-06-09 22:19 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +//		NOTE: フォームに空欄がある(result.hasError()がtrue)だと、パスワード不一致やメールアドレス重複のエラーメッセージが表示されない。
やり方が思いつかない場合はご相談ください。

2022-06-09 22:19 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/AdministratorService.java
> +		return false;
行なっていることは問題ありませんが、以下の方針に修正をお願い致します。
入力値チェックと同じようなタイミング(コントローラの最初の方)でチェックを終わらせるようなイメージです。

○今回の方針
　・AdministratorServiceにseachByMailAddress()を作る
　・AdministratorControllerで上記のメソッドを呼ぶ
　・もしnullなら入力画面に戻りエラーメッセージを出す
　・もしnullじゃなければ(Administratorオブジェクトが返ってきたら)登録処理を行う

2022-06-10 02:00 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-10 02:00 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +
とても良いですが、実はもっとシンプルにわかりやすく書けます。

if (result.hasErrors()) {
	・・・
}

上記の処理はresultにエラーが１つでもあればtrueが返ります。

result.rejectValue(・・・);

はresultにエラーを登録している処理のため、

if (result.hasErrors()) {
	・・・
}

を一番下に書けば解決します。

2022-06-10 06:40 UTC, merged